<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<Using Include="Shared.Ui.BaseDialogs.StandardDialog.UnifiedMessageBox" Alias="MessageBox" />
	</ItemGroup>
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SharedUI\Shared.Ui.csproj" />
    <ProjectReference Include="..\ContentProject\ContentProject.csproj" />
    <ProjectReference Include="..\MeshDecimator\MeshDecimator.csproj" />
  </ItemGroup>

</Project>
